// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: leavetype.sql

package database

import (
	"context"
)

const createLeaveType = `-- name: CreateLeaveType :exec
INSERT INTO
  LeaveTypes (leave_type_name, default_entitlement)
VALUES
  ($1, $2)
`

type CreateLeaveTypeParams struct {
	LeaveTypeName      string
	DefaultEntitlement int32
}

func (q *Queries) CreateLeaveType(ctx context.Context, arg CreateLeaveTypeParams) error {
	_, err := q.db.ExecContext(ctx, createLeaveType, arg.LeaveTypeName, arg.DefaultEntitlement)
	return err
}

const deleteLeaveType = `-- name: DeleteLeaveType :exec
DELETE FROM
  LeaveTypes
WHERE
  leave_type_id = $1
`

func (q *Queries) DeleteLeaveType(ctx context.Context, leaveTypeID int32) error {
	_, err := q.db.ExecContext(ctx, deleteLeaveType, leaveTypeID)
	return err
}

const updateLeaveType = `-- name: UpdateLeaveType :exec
UPDATE
  LeaveTypes
SET
  leave_type_id = $1,
  default_entitlement = $2
WHERE
  leave_type_id = $3
`

type UpdateLeaveTypeParams struct {
	LeaveTypeID        int32
	DefaultEntitlement int32
	LeaveTypeID_2      int32
}

func (q *Queries) UpdateLeaveType(ctx context.Context, arg UpdateLeaveTypeParams) error {
	_, err := q.db.ExecContext(ctx, updateLeaveType, arg.LeaveTypeID, arg.DefaultEntitlement, arg.LeaveTypeID_2)
	return err
}
