// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: leavebalance.sql

package database

import (
	"context"
	"database/sql"
)

const createBalance = `-- name: CreateBalance :exec
INSERT INTO
  LeaveBalances(user_id, leave_type_id, balance)
VALUES
($1, $2, $3)
`

type CreateBalanceParams struct {
	UserID      sql.NullInt32
	LeaveTypeID sql.NullInt32
	Balance     int32
}

func (q *Queries) CreateBalance(ctx context.Context, arg CreateBalanceParams) error {
	_, err := q.db.ExecContext(ctx, createBalance, arg.UserID, arg.LeaveTypeID, arg.Balance)
	return err
}

const updateLeaveBalance = `-- name: UpdateLeaveBalance :exec
UPDATE
  LeaveBalances
SET
  balance = $1
WHERE
  balance_id = $2
`

type UpdateLeaveBalanceParams struct {
	Balance   int32
	BalanceID int32
}

func (q *Queries) UpdateLeaveBalance(ctx context.Context, arg UpdateLeaveBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateLeaveBalance, arg.Balance, arg.BalanceID)
	return err
}
