// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: role.sql

package database

import (
	"context"
)

const createRole = `-- name: CreateRole :exec
INSERT INTO
  Roles(role_name)
VALUES
  ($1)
`

func (q *Queries) CreateRole(ctx context.Context, roleName string) error {
	_, err := q.db.ExecContext(ctx, createRole, roleName)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM
  Roles
WHERE
  role_id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, roleID int32) error {
	_, err := q.db.ExecContext(ctx, deleteRole, roleID)
	return err
}

const updateRole = `-- name: UpdateRole :exec
UPDATE
  Roles
SET
  role_name = $1
WHERE
  role_id = $1
`

func (q *Queries) UpdateRole(ctx context.Context, roleName string) error {
	_, err := q.db.ExecContext(ctx, updateRole, roleName)
	return err
}
