// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: users.sql

package database

import (
	"context"
	"database/sql"
)

const authenticateUser = `-- name: AuthenticateUser :exec
SELECT
  user_id, username, password, email, role_id
FROM
  Users
WHERE
  email = $1
  AND password = $2
`

type AuthenticateUserParams struct {
	Email    string
	Password string
}

func (q *Queries) AuthenticateUser(ctx context.Context, arg AuthenticateUserParams) error {
	_, err := q.db.ExecContext(ctx, authenticateUser, arg.Email, arg.Password)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO
  Users(username, password, email, role_id)
VALUES
  ($1, $2, $3, $4)
`

type CreateUserParams struct {
	Username string
	Password string
	Email    string
	RoleID   sql.NullInt32
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.RoleID,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM
  Users
WHERE
  user_id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, userID int32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, userID)
	return err
}

const findUserById = `-- name: FindUserById :one
SELECT
  user_id, username, password, email, role_id
FROM
  Users
WHERE
  user_id = $1
`

func (q *Queries) FindUserById(ctx context.Context, userID int32) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserById, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.RoleID,
	)
	return i, err
}

const findUsersByRole = `-- name: FindUsersByRole :many
SELECT
  user_id, username, password, email, role_id
FROM
  Users
WHERE
  role_id = $1
`

func (q *Queries) FindUsersByRole(ctx context.Context, roleID sql.NullInt32) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, findUsersByRole, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Password,
			&i.Email,
			&i.RoleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE
  Users
SET
  username = $1,
  password = $2
WHERE
  user_id = $3
`

type UpdateUserParams struct {
	Username string
	Password string
	UserID   int32
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Username, arg.Password, arg.UserID)
	return err
}
